FROM node:10-alpine

USER root

RUN apk add --update \
     python \
     python-dev \
     py-pip \
     build-base \
   && pip install virtualenv \
   && rm -rf /var/cache/apk/*

RUN pip install --upgrade pip
